// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_numerov
List rcpp_numerov();
RcppExport SEXP numerovmpreal_rcpp_numerov() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(rcpp_numerov());
    return __result;
END_RCPP
}
// setPotential
void setPotential(NumericVector px, NumericVector py);
RcppExport SEXP numerovmpreal_setPotential(SEXP pxSEXP, SEXP pySEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type px(pxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type py(pySEXP);
    setPotential(px, py);
    return R_NilValue;
END_RCPP
}
// setLeftTail
void setLeftTail(NumericVector leftTail);
RcppExport SEXP numerovmpreal_setLeftTail(SEXP leftTailSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type leftTail(leftTailSEXP);
    setLeftTail(leftTail);
    return R_NilValue;
END_RCPP
}
// setRightTail
void setRightTail(NumericVector rightTail);
RcppExport SEXP numerovmpreal_setRightTail(SEXP rightTailSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type rightTail(rightTailSEXP);
    setRightTail(rightTail);
    return R_NilValue;
END_RCPP
}
// getPotential
List getPotential();
RcppExport SEXP numerovmpreal_getPotential() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(getPotential());
    return __result;
END_RCPP
}
// computeSpectrum
void computeSpectrum(int nEigen, double dE, double tol);
RcppExport SEXP numerovmpreal_computeSpectrum(SEXP nEigenSEXP, SEXP dESEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type nEigen(nEigenSEXP);
    Rcpp::traits::input_parameter< double >::type dE(dESEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    computeSpectrum(nEigen, dE, tol);
    return R_NilValue;
END_RCPP
}
// getEnergies
NumericVector getEnergies();
RcppExport SEXP numerovmpreal_getEnergies() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(getEnergies());
    return __result;
END_RCPP
}
// getWavefunctions
List getWavefunctions();
RcppExport SEXP numerovmpreal_getWavefunctions() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(getWavefunctions());
    return __result;
END_RCPP
}
