# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_numerov <- function() {
    .Call('numerovmpreal_rcpp_numerov', PACKAGE = 'numerovmpreal')
}

setPotential <- function(px = numeric(), py = numeric()) {
    invisible(.Call('numerovmpreal_setPotential', PACKAGE = 'numerovmpreal', px, py))
}

setLeftTail <- function(leftTail) {
    invisible(.Call('numerovmpreal_setLeftTail', PACKAGE = 'numerovmpreal', leftTail))
}

setRightTail <- function(rightTail) {
    invisible(.Call('numerovmpreal_setRightTail', PACKAGE = 'numerovmpreal', rightTail))
}

getPotential <- function() {
    .Call('numerovmpreal_getPotential', PACKAGE = 'numerovmpreal')
}

computeSpectrum <- function(nEigen, dE = 0.1, tol = 1e-9) {
    invisible(.Call('numerovmpreal_computeSpectrum', PACKAGE = 'numerovmpreal', nEigen, dE, tol))
}

getEnergies <- function() {
    .Call('numerovmpreal_getEnergies', PACKAGE = 'numerovmpreal')
}

getWavefunctions <- function() {
    .Call('numerovmpreal_getWavefunctions', PACKAGE = 'numerovmpreal')
}

